#version : "3.3"
#services :
 #  container_name: web
  #  image: 698subhashchandra/django-app:latest
   # env_file:
    #  - ../django-application/env
    #ports:
     # - "31000:8000"
    #volumes:
     # - ./volume/store_data/db.sqlite3:/data/db.sqlite3
#volumes:
 # data:
version : "3.3"
services:
  backend:
    container_name: web
    image: 698subhashchandra/django-app:latest
    env_file:
      - ../django-application/env
    ports:
      - "31000:8000"
    volumes:
      - ./volume/store_data/db.sqlite3:/data/db.sqlite3

volumes:
  data:
